name: larvitsession CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mariadb version: '10.7'
        mysql database: 'test'
        mysql root password: 'test'

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - shell: bash
      run: |
        cat << EOF > ./config/db_test.json
        {
          "connectionLimit": 10,
          "host": "127.0.0.1",
          "port": 3306,
          "user": "root",
          "password": "test",
          "charset": "utf8mb4_general_ci",
          "supportBigNumbers": true,
          "database": "test"
        }
        EOF
    - run: npm test
